ecare-software/ecare-residential

.vscode/settings.json
client/src/App.js
client/src/components/MessageBoard/MessageBoard.js
client/src/components/NavBar/bsNavBar.js
client/src/components/Reports/ReportsContainer.js
client/src/components/UserManagement/CreateNewUser.js
routes/api/email.js

pushing bug fix branch

---

client/src/App.js
client/src/components/DirectMessageBoard/DirectMessageBoard.js

user mapping seemingly resolved

---

client/src/App.js
client/src/components/MessageBoard/MessageBoard.js
models/DiscussionMessage.js
routes/api/discussionMessages.js

discussion board by ids

---

.deployment
client/src/App.js
models/DirectMessage.js
routes/api/directMessages.js
routes/api/discussionMessages.js

getting dms by user and home id

---

client/src/App.css
client/src/components/LogInContainer/LogInContainer.css
client/src/components/LogInContainer/LogInContainer.js
client/src/components/NavBar/bsNavBar.js

modal fixed

---

client/src/App.css
client/src/App.js
client/src/components/Header/Header.css
client/src/components/Header/Header.js
client/src/components/Modals/RequestDemoModal.js
client/src/components/NavBar/bsNavBar.js

resolved issues with learn more modal

---

client/src/App.js
client/src/components/Header/Header.js
client/src/components/NavBar/bsNavBar.js
routes/api/email.js

added now org demo field

---

client/src/App.js
client/src/components/ManageAccount/ManageAccountContainer.js
models/User.js
package-lock.json
package.json
routes/api/users.js

added user signature to user modal and manage user account

---

app.js
client/src/App.js
client/src/components/Forms/AdmissionAssessment.js
client/src/components/Forms/BodyCheck.js
client/src/components/Forms/IllnessInjury.js
client/src/components/Forms/IncidentReport.js
client/src/components/Forms/RestraintReport.js
client/src/components/Forms/SeriousIncidentReport.js
client/src/components/Forms/TreatmentPlan72.js
client/src/components/NavBar/bsNavBar.js
client/src/components/Reports/FormReports.js
client/src/components/Reports/ShowFormContainer.js
models/SeriousIncidentReport.js
routes/api/SeriousIncidentReport.js

added serious incident form

---

client/src/components/Reports/FormReports.js
client/src/components/Reports/ReportsContainer.css
client/src/components/Reports/ReportsContainer.js
client/src/components/Reports/TrainingReports.js

showing form filters

---

client/src/components/Documents/Documents.js

added spinner to docs

---

client/src/components/Reports/ShowFormContainer.js

updated approval text and color

---

client/src/components/Reports/ReportsContainer.js

hiding training reports from non admin roles

---

client/src/components/Forms/FormListContainer.js
client/src/components/Reports/FormReports.js
client/src/components/Reports/SearchContainer.js
client/src/utils/ClientOption.util.js
routes/api/SeriousIncidentReport.js
routes/api/admissionAssessment.js
routes/api/bodyCheck.js
routes/api/dailyProgressAndActivity.js
routes/api/illnessInjury.js
routes/api/incidentReport.js
routes/api/restraintReport.js
routes/api/treatmentPlans72.js

show approval count

---

client/src/App.css
client/src/App.js
client/src/components/MessageBoard/MessageBoard.js
client/src/components/Reports/FormReports.js

hide discussion message for non admin roles

---

client/src/App.js
client/src/components/MessageBoard/MessageBoard.js

refresh board

---

client/src/components/Forms/AdmissionAssessment.js
client/src/components/Forms/BodyCheck.js
client/src/components/Forms/DailyProgressAndActivity.js
client/src/components/Forms/IllnessInjury.js
client/src/components/Forms/IncidentReport.js
client/src/components/Forms/RestraintReport.js
client/src/components/Forms/SeriousIncidentReport.js
client/src/components/Forms/TreatmentPlan72.js
client/src/components/NavBar/bsNavBar.js
client/src/utils/FormSuccessAlert.js

form post submit message

---

client/src/App.js

added margin to left btns

---

client/src/App.js
client/src/components/Forms/AdmissionAssessment.js
client/src/components/Forms/BodyCheck.js
client/src/components/Forms/DailyProgressAndActivity.js
client/src/components/Forms/IllnessInjury.js
client/src/components/Forms/IncidentReport.js
client/src/components/Forms/RestraintReport.js
client/src/components/Forms/SeriousIncidentReport.js
client/src/components/Forms/TreatmentPlan72.js
client/src/components/Reports/FormReports.js
client/src/components/Reports/SearchContainer.js
client/src/utils/FormSuccessAlert.js

quick fixes after demo

---

client/src/App.js
client/src/components/Forms/AdmissionAssessment.js
client/src/components/Forms/BodyCheck.js
client/src/components/Forms/DailyProgressAndActivity.js
client/src/components/Forms/IllnessInjury.js
client/src/components/Forms/IncidentReport.js
client/src/components/Forms/RestraintReport.js
client/src/components/Forms/SeriousIncidentReport.js
client/src/components/Forms/TreatmentPlan72.js
client/src/components/ManageAccount/ManageAccountContainer.js

vvalidate user submittion

---

app.js
client/src/App.js
client/src/components/Forms/AdmissionAssessment.js
client/src/components/Forms/AwakeNightStaffSignoff.js
client/src/components/Forms/BodyCheck.js
client/src/components/Forms/DailyProgressAndActivity.js
client/src/components/Forms/IllnessInjury.js
client/src/components/Forms/IncidentReport.js
client/src/components/Forms/RestraintReport.js
client/src/components/Forms/SeriousIncidentReport.js
client/src/components/Forms/TreatmentPlan72.js
client/src/components/NavBar/bsNavBar.js
client/src/components/Reports/FormReports.js
client/src/components/Reports/ShowFormContainer.js
client/src/utils/FormSuccessAlert.js
models/AwakeNightStaffSignoff.js
package-lock.json
package.json
routes/api/admissionAssessment.js
routes/api/allFormRoutes.js
routes/api/awakeNightStaffSignoff.js

awake night staff form

---

client/src/components/Forms/AwakeNightStaffSignoff.js
models/AwakeNightStaffSignoff.js

updated awake night sign off

---

models/AwakeNightStaffSignoff.js

missing approval prop

---

client/src/components/Testimonial/Testimonial.js

Signed-off-by: Ty D'Angelo <tydangelo18@gmail.com>

Removed unnecessary comment from component.

---

app.js
client/src/App.js
client/src/components/Forms/NightMonitoring.js
client/src/components/NavBar/bsNavBar.js
client/src/components/NightMonitoringChildRow.js
client/src/components/Reports/FormReports.js
client/src/components/Reports/ShowFormContainer.js
models/NightMonitoring.js
routes/api/allFormRoutes.js
routes/api/nightMonitoring.js
routes/api/test.txt

testing night mon

---

client/src/components/Forms/BodyCheck.js
models/BodyCheck.js
routes/api/bodyCheck.js

added face field to form

---

.github/workflows/codesee-arch-diagram.yml
client/src/App.js
client/src/components/Forms/TESTTreatmentPlan72.js
client/src/components/Reports/ShowFormContainer.js

This is a test refactor for this component so you can take a look at my code style

TEST Refactor for TreatmentPlan72 Form Component

---

client/src/App.css
client/src/components/Forms/AdmissionAssessment.js
client/src/components/Forms/AwakeNightStaffSignoff.js
client/src/components/Forms/BodyCheck.js
client/src/components/Forms/DailyProgressAndActivity.js
client/src/components/Forms/IllnessInjury.js
client/src/components/Forms/IncidentReport.js
client/src/components/Forms/NightMonitoring.js
client/src/components/Forms/RestraintReport.js
client/src/components/Forms/SeriousIncidentReport.js
client/src/components/LogInContainer/LogInContainer.css
client/src/components/NightMonitoringChildRow.js
client/src/components/Reports/ShowFormContainer.js

Reformat Incident reports and Awake Night Sign Offs.

---

client/src/App.css
client/src/components/Forms/FormSubmitterListContainer.js

Fixes Issue #291 - "Update report table"
serious incident, restraint report, and incident report forms show
- the create date (without time)
- submitter name
- the client name
- (incident date/restraint date)
all other forms show:
- the create date (without time)
- submitter name
- the client name

Update report table

---

client/src/App.css
client/src/components/Forms/AdmissionAssessment.js
client/src/components/Forms/AwakeNightStaffSignoff.js
client/src/components/Forms/BodyCheck.js
client/src/components/Forms/DailyProgressAndActivity.js
client/src/components/Forms/FormSubmitterListContainer.js
client/src/components/Forms/IllnessInjury.js
client/src/components/Forms/IncidentReport.js
client/src/components/Forms/NightMonitoring.js
client/src/components/Forms/RestraintReport.js
client/src/components/Forms/SeriousIncidentReport.js
client/src/components/Forms/TreatmentPlan72.js
client/src/components/NightMonitoringChildRow.js
client/src/components/Reports/FormReports.js
client/src/components/Reports/ReportsContainer.js
client/src/components/Reports/ShowFormContainer.js

- Removed blank first page when user prints by form type
- Disabled 'finish later' and 'submit' buttons + all form fields other than 'child's name' and 'create date' until user selects child's name
- Fixed existing "FromReports" typo
- Reformatted 'finish later' and 'submit' buttons

Form Validation & Print (branch → dev)

---

client/src/components/Forms/AdmissionAssessment.js
client/src/components/Forms/BodyCheck.js
client/src/components/Forms/DailyProgressAndActivity.js
client/src/components/Forms/IllnessInjury.js
client/src/components/Forms/IncidentReport.js
client/src/components/Forms/NightMonitoring.js
client/src/components/Forms/RestraintReport.js
client/src/components/Forms/SeriousIncidentReport.js
client/src/components/Forms/TreatmentPlan72.js
client/src/components/NightMonitoringChildRow.js

- Allow user to select & save create date other than current date
- Fix to display success alert when user saves/submits a Night Monitoring Form

'Create Date' back date fix → dev

---

client/src/components/UserManagement/ManageUsers.js

- Fixed bug so "Admin" users can now edit user accounts

admin users can now edit user accounts

---

client/src/App.css
client/src/components/Forms/AdmissionAssessment.js
client/src/components/Forms/AwakeNightStaffSignoff.js
client/src/components/Forms/BodyCheck.js
client/src/components/Forms/DailyProgressAndActivity.js
client/src/components/Forms/FormSubmitterListContainer.js
client/src/components/Forms/IllnessInjury.js
client/src/components/Forms/IncidentReport.js
client/src/components/Forms/NightMonitoring.js
client/src/components/Forms/RestraintReport.js
client/src/components/Forms/SeriousIncidentReport.js
client/src/components/Forms/TreatmentPlan72.js
client/src/utils/HandleFieldInputDate.js

Create Date Util + Show Create Date On Print + Enable Create Date Editing

---

client/src/components/UserManagement/UpdateUser.js

We need to allow uses to select from list of predetermined job titles instead of open input
https://github.com/ecare-software/ecare-residential/assets/21225391/fdf6270f-0529-4306-af4c-dca32c215e49

manage users needs to have job table dropdown

---

client/src/App.js
client/src/components/Forms/BodyCheck.js
client/src/components/Forms/DailyProgressAndActivity.js
client/src/components/Forms/IncidentReport.js
client/src/components/Forms/SeriousIncidentReport.js

* Summary of Behavior at School, Summary of Behavior at Home, Summary of Daily Schedule each moved to a full line at bottom of the page when creating report, editing report, and printing report
* show all text for illness/injury when printing report
* show all text for all fields when printing report
* explain incident & result of incident to full line at bottom of page when creating report, editing report & printing report
* changed numbers in dropdown to mark type (marks will still be saved as numbers in database)
* updated instruction language
* additional details to full line at bottom of page when creating report, editing report & printing report
* NOTE: dropdown option 11 does not correlate with any mark outline on the instructions (see photo below)
NOTE

Summary Questions Full Line & Body Check Dropdown 

---

client/src/App.js
client/src/components/Forms/AwakeNightStaffSignoff.js
client/src/components/Forms/DailyProgressAndActivity.js
client/src/components/Forms/FormSubmitterListContainer.js
models/DailyProgressAndActivity.js
models/Home.js
routes/api/dailyProgressAndActivity.js
routes/api/home.js

- if homeId = 'home-3' (right at home), then require 2 signatures before form status is 'COMPLETED'
- 'IN PROGRESS' status shows as bolded yellow font when 1 signature is submitted but still waiting on 2nd signature

Daily Activity Two Signatures

---

client/src/components/UserManagement/ManageUsers.js

- clicking 'reset password' resets the correct users password
- removed red background
- removed auto-populated text in first password field

User Management - Reset Password of Selected User
